# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "PAGK"
  identifier = "aboutpagk"
  url = "#"
  weight = 1

[[main]]
  name = "PAGK 소개"
  parent = "aboutpagk"
  url = "/aboutpagk/"
  weight = 10

[[main]]
  name = "연혁"
  parent = "aboutpagk"
  url = "/history/"
  weight = 15

[[main]]
  name = "회칙"
  parent = "aboutpagk"
  url = "/policy/"
  weight = 20

[[main]]
  name = "운영위원회"
  parent = "aboutpagk"
  url = "/aboutpagk/board/"
  weight = 30

[[main]]
  name = "Posts"
  url = "/post/"
  weight = 3

[[main]]
  name = "Photos"
  url = "/categories/photos/"
  weight = 4

[[main]]
  name = "Meetings"
  url = "/tutorial/"
  weight = 5

[[main]]
  name = "Forum↗"
  url = "https://groups.google.com/a/pagk.or.kr/forum/#!forum/list/"
  weight = 6

[[main]]
  name = "Links"
  url = "/links/"
  weight = 7

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 8

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 7
#
